// Global Variables
var canChangeCard = true;
var ordersDict = {};
var cardAuthDict = {};
var accounts = [];
var authAmount = "0";
var undeliveredGoodsValue = 0;
var uncapturedInvoicesValue = 0;
var cono = "";
var divi = "";
var environment = "";
var orderCountry = "";
var currency = "";
var token = "";
var accttype = "";
var properties;
var associatedToken = "";
var retref = "";
var authcode = "";
var authdate = "";
var expiry = "";
var transaction_status = "";
var cardservices_profile_id = "";
var cardconnect_account_id = "";
var profileHasAccounts = false;
var newCardAppliedToOrder = false;
var orderAlreadyHasCard = false;
var accounts_loaded = false;